# Generated by Django 4.1.4 on 2026-02-25 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tubes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tubetype",
            options={"verbose_name": "Тип трубы", "verbose_name_plural": "Тип труб"},
        ),
        migrations.AlterModelOptions(
            name="type",
            options={"verbose_name": "Труба", "verbose_name_plural": "Трубы"},
        ),
    ]
