# Generated by Django 4.1.4 on 2026-03-26 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tubes", "0002_alter_tubetype_options_alter_type_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="type",
            name="kvelocity",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                max_digits=15,
                verbose_name="Скоростной коэфицент",
            ),
            preserve_default=False,
        ),
    ]
