# Generated by Django 4.1.4 on 2026-03-10 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="otv",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("distance", models.FloatField()),
                ("speed", models.IntegerField()),
                ("n_vetk", models.IntegerField()),
                ("n_otv", models.IntegerField()),
                ("d1", models.FloatField()),
                ("d2", models.FloatField()),
                ("d3", models.FloatField()),
                ("d4", models.FloatField()),
                ("d5", models.FloatField()),
                ("d6", models.FloatField()),
                ("d7", models.FloatField()),
                ("d8", models.FloatField()),
                ("d9", models.FloatField()),
                ("d10", models.FloatField()),
                ("d11", models.FloatField()),
                ("d12", models.FloatField()),
                ("d13", models.FloatField()),
                ("d14", models.FloatField()),
                ("d15", models.FloatField()),
                ("d16", models.FloatField()),
                ("d17", models.FloatField()),
                ("d18", models.FloatField()),
                ("d19", models.FloatField()),
                ("d20", models.FloatField()),
                ("d21", models.FloatField()),
                ("Max_L_C", models.IntegerField()),
                ("Max_L_B", models.IntegerField()),
                ("Max_L_A", models.IntegerField()),
                ("Max_L2_C", models.IntegerField()),
                ("Max_L2_B", models.IntegerField()),
                ("Max_L2_A", models.IntegerField()),
                ("vers", models.IntegerField()),
                ("q_C", models.IntegerField()),
                ("q_B", models.IntegerField()),
                ("q_A", models.IntegerField()),
            ],
        ),
    ]
