# Generated by Django 4.1.4 on 2026-02-19 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("python", "0002_otv"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LogMessage",
        ),
        migrations.AddField(
            model_name="otv",
            name="q_A",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="otv",
            name="q_B",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="otv",
            name="q_C",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="otv",
            name="vers",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
