# Generated by Django 4.1.4 on 2026-02-25 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management_node", "0006_controlunit_installation_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="controlunit",
            options={
                "verbose_name": "узел управления",
                "verbose_name_plural": "узлы управления",
            },
        ),
        migrations.AlterModelOptions(
            name="controlunitname",
            options={
                "verbose_name": "наименование узла управления",
                "verbose_name_plural": "наименование узлов управления",
            },
        ),
    ]
